### ISSUE TITLE
the web page will automatically zoom in and out in mobile web pages.

### ISSUE THREAD

**Issue by wkByte** [BlueArchive-Website/BugReport#1]
In mobile web pages, when users focus on input components such as drop-down boxes, the web page will automatically zoom in and out. You can add the following code under the `<head>` tag to solve this problem.
`<meta name="viewport" content="width=device width, initial scale=1.0, minimum scale=1.0, maximum scale=1.0, user scale=no"/>`

**Comment by benx1n** [comment]
has append this code, can you try again for that?
