### ISSUE TITLE
 web app programs support

### ISSUE THREAD

**Issue by wkByte** [BlueArchive-Website/BugReport#2]
I think it would be better if this website could enable support for web app programs in Safari browser.
Add code ` <meta name="apple-mobile-web-app-capable" content="yes">` under `head` tag

**Comment by JustOneSummer** [comment]
android seems to use ```<meta name="mobile-web-app-capable" content="yes">```

**Comment by benx1n** [comment]
extra add the touch-icon, can you please validate for that?
